Add files via upload

diff --git a/start b/start
--- a/start
+++ b/start
@@ -11,7 +11,7 @@ LFS=$LFS
 nvme0="nvme0n1"
 nvme1="nvme1n1"
 label="sdb"
-# Note- the sdb disk has been removed (03/2022)
+# Note - the sdb disk has been removed (03/2022) Its now used as a swap partition
 # the code for it has been left in place. sdb may reappear in the future
 # but it is not maintained here currently
 diskLabel=$label
@@ -20,17 +20,17 @@ disk4=""
 # nvme0n1p3 - p5 Ubuntu
 # nvme0n1p6 - p8 Arch Linux
 # nvme0n1p9 - p12 LFS (Gnome)
-# nvme0n1p13 - swap
-# nvme1n1p6 - p8 Arch (usually xfce)
+# nvme1n1p6 - p8 LFS (usually xfce)
 # nvme1n1p9 - p12 LFS (xfce or other)
-# nvme1n1p13 - swap
-# sdb used to contain these partitions
+# sdb (1TB) used to contain these partitions
 # sdb1 - EFI system partition
 # sdb2 - BIOS boot partition
 # sdb3 - 5    LFS xfce 
 # sdb6 - 9    LFS kf5 plasma
 # sdb10 - 12  Arch KF5 plasma
 # sdb13       swap
+#
+# but now sda1 is used as a swap partition
 #
 # which disk is mounted
 isNvme0=false
@@ -95,6 +95,9 @@ isDevMounted () { findmnt -rno SOURCE        "$1" >/dev/null;} #device only
 isPathMounted() { findmnt -rno        TARGET "$1" >/dev/null;} #path   only
 #where: -r = --raw, -n = --noheadings, -o = --output
 #
+runit=true # by default the requested partitions are mounted
+# if sdb chosen then set runit=false
+#
 # determine which partitions are already mounted
 echo "Looking for partitions that are mounted:"
 if [ "$LFS" = /mnt/lfs ]; then
@@ -155,7 +158,7 @@ if [ "$LFS" = /mnt/lfs ]; then
     suite1="${label}3, 4 and 5 (LFS)"
     suite2="${label}6, 7, 8 and 9 (LFS)"
     suite3="${label}10, 11 and 12 (Arch KF5 plasma)"
-    suite4="${nvme1}p6, p7 and p8 (Arch xfce)"
+    suite4="${nvme1}p6, p7 and p8 (LFS xfce)"
     suite5="${nvme1}p9, p10, p11 and p12 (LFS xfce)"
     case $rootSystem in
        *p7) # Arch is mounted
@@ -200,25 +203,28 @@ if [ "$LFS" = /mnt/lfs ]; then
     select opt in "${options[@]}" "Quit"; do
         case "$REPLY" in
            1)
-              echo "Will create a file system on partitions $suite1"
+              echo "If sdb existed, would create a file system on partitions $suite1"
               disk1=3
               disk2=4
               disk3=5
+              runit=false
               break
            ;;
            2)
-              echo "Will create a file system on partitions $suite2"
+              echo "If sdb existed, would create a file system on partitions $suite2"
               disk1=6
               disk2=7
               disk3=8
               disk4=9
+              runit=false
               break
            ;;
            3)
-              echo "Will create a file system on partitions $suite3"
+              echo "If sdb existed, would create a file system on partitions $suite3"
               disk1=10
               disk2=11
               disk3=12
+              runit=false
               break
            ;;
            4)
@@ -281,7 +287,7 @@ if [ "$LFS" = /mnt/lfs ]; then
          four="p12"
        ;;
        *p10) # LFS is mounted
-         suite7="${nvme1}p6, p7, p8 (Arch xfce)"
+         suite7="${nvme1}p6, p7, p8 (LFS xfce)"
          one="p6"
          two="p7"
          three="p8"
@@ -296,25 +302,28 @@ if [ "$LFS" = /mnt/lfs ]; then
     select opt in "${options[@]}" "Quit"; do
         case "$REPLY" in
            1)
-              echo "Will create a file system on partitions $suite1"
+              echo "If sdb existed, would create a file system on partitions $suite1"
               disk1=3
               disk2=4
               disk3=5
+              runit=false
               break
            ;;
            2)
-              echo "Will create a file system on partitions $suite2"
+              echo "If sdb existed, would create a file system on partitions $suite2"
               disk1=6
               disk2=7
               disk3=8
               disk4=9
+              runit=false
               break
            ;;
            3)
-              echo "Will create a file system on partitions $suite3"
+              echo "If sdb existed, would create a file system on partitions $suite3"
               disk1=10
               disk2=11
               disk3=12
+              runit=false
               break
            ;;
            4)
@@ -360,124 +369,125 @@ if [ "$LFS" = /mnt/lfs ]; then
            ;;
         esac
     done
-  elif $isDisk; then # offer to create a file system on partitions on remaining label partitions, nvme0 and nvme1
-    suite1="${nvme0}p3, p4 and p5 (Ububtu)"
-    suite2="${nvme0}p6, p7 and p8 (Arch rolling)"
-    suite3="${nvme0}p9, p10, p11 and p12 (LFS)"
-    suite4="${nvme1}p6, p7 and p8 (Arch xfce)"
-    suite5="${nvme1}p9, p10, p11 and p12 (LFS)"
-    case $rootSystem in
-       *sdb4)
-         one="6"
-         two="7"
-         three="8"
-         four="9"
-         suite6="${label}6, 7, 8 and 9"
-         five="10"
-         six="11"
-         seven="12"
-         eight=""
-         suite7="${label}10, 11 and 12"
-       ;;
-       *sdb7)
-         one="3"
-         two="4"
-         three="5"
-         four=""
-         suite6="${label}3, 4 and 5"
-         five="10"
-         six="11"
-         seven="12"
-         eight=""
-         suite7="${label}10, 11 and 12"
-       ;;
-       *sdb11)
-         one="3"
-         two="4"
-         three="5"
-         four=""
-         suite6="${label}3, 4 and 5"
-         five="6"
-         six="7"
-         seven="8"
-         eight="9"
-         suite7="${label}6, 7, 8 and 9"
-       ;;
-    esac
-    echo "will chroot into one of the following -"
-    echo "Choose one:"
-    echo " "
-    PS3="> "
-    options=("$suite1" "$suite2" "$suite3" "$suite4" "$suite5" "$suite6" "$suite7")
-    select opt in "${options[@]}" "Quit"; do
-        case "$REPLY" in
-           1)
-              echo "Will create a file system on partitions $suite1"
-              disk1=p3
-              disk2=p4
-              disk3=p5
-              diskLabel=$nvme0
-              break
-           ;;
-           2)
-              echo "Will create a file system on partitions $suite2"
-              disk1=p6
-              disk2=p7
-              disk3=p8
-              diskLabel=$nvme0
-              break
-           ;;
-           3)
-              echo "Will create a file system on partitions $suite3"
-              disk1=p9
-              disk2=p10
-              disk3=p11
-              disk4=p12
-              diskLabel=$nvme0
-              break
-           ;;
-           4)
-              echo "Will create a file system on partitions $suite4"
-              disk1=p6
-              disk2=p7
-              disk3=p8
-              diskLabel=$nvme1
-              break
-           ;;
-           5)
-              echo "Will create a file system on partitions $suite5"
-              disk1=p9
-              disk2=p10
-              disk3=p11
-              disk4=p12
-              diskLabel=$nvme1
-              break
-           ;;
-           6)
-              echo "Will create a file system on partitions $suite6"
-              disk1=$one
-              disk2=$two
-              disk3=$three
-              if [ ! -z "$four" ]; then disk4=$four; fi
-              break
-           ;;
-           7)
-              echo "Will create a file system on partitions $suite7"
-              disk1=$five
-              disk2=$six
-              disk3=$seven
-              if [ ! -z "$eight" ]; then disk4=$eight; fi
-              break
-           ;;
-           $((${#options[@]}+1)))
-              echo "Okay, will exit"
-              exit 1
-           ;;
-           *) echo "Invalid option. Type 1, 2, 3, 4, 5, 6, 7 or 8"
-              :
-           ;;
-        esac
-    done
+# disk sdb1 not currently used so cannot be the host. Left the code in place as this may change
+#  elif $isDisk; then # offer to create a file system on partitions on remaining label partitions, nvme0 and nvme1
+#    suite1="${nvme0}p3, p4 and p5 (Ububtu)"
+#    suite2="${nvme0}p6, p7 and p8 (Arch rolling)"
+#    suite3="${nvme0}p9, p10, p11 and p12 (LFS)"
+#    suite4="${nvme1}p6, p7 and p8 (LFS xfce)"
+#    suite5="${nvme1}p9, p10, p11 and p12 (LFS)"
+#    case $rootSystem in
+#       *sdb4)
+#         one="6"
+#         two="7"
+#         three="8"
+#         four="9"
+#         suite6="${label}6, 7, 8 and 9"
+#         five="10"
+#         six="11"
+#         seven="12"
+#         eight=""
+#         suite7="${label}10, 11 and 12"
+#       ;;
+#       *sdb7)
+#         one="3"
+#         two="4"
+#         three="5"
+#         four=""
+#         suite6="${label}3, 4 and 5"
+#         five="10"
+#         six="11"
+#         seven="12"
+#         eight=""
+#         suite7="${label}10, 11 and 12"
+#       ;;
+#       *sdb11)
+#         one="3"
+#         two="4"
+#         three="5"
+#         four=""
+#         suite6="${label}3, 4 and 5"
+#         five="6"
+#         six="7"
+#         seven="8"
+#         eight="9"
+#         suite7="${label}6, 7, 8 and 9"
+#       ;;
+#    esac
+#    echo "will chroot into one of the following -"
+#    echo "Choose one:"
+#    echo " "
+#    PS3="> "
+#    options=("$suite1" "$suite2" "$suite3" "$suite4" "$suite5" "$suite6" "$suite7")
+#    select opt in "${options[@]}" "Quit"; do
+#        case "$REPLY" in
+#           1)
+#              echo "Will create a file system on partitions $suite1"
+#              disk1=p3
+#              disk2=p4
+#              disk3=p5
+#              diskLabel=$nvme0
+#              break
+#           ;;
+#           2)
+#              echo "Will create a file system on partitions $suite2"
+#              disk1=p6
+#              disk2=p7
+#              disk3=p8
+#              diskLabel=$nvme0
+#              break
+#           ;;
+#           3)
+#              echo "Will create a file system on partitions $suite3"
+#              disk1=p9
+#              disk2=p10
+#              disk3=p11
+#              disk4=p12
+#              diskLabel=$nvme0
+#              break
+#           ;;
+#           4)
+#              echo "Will create a file system on partitions $suite4"
+#              disk1=p6
+#              disk2=p7
+#              disk3=p8
+#              diskLabel=$nvme1
+#              break
+#           ;;
+#           5)
+#              echo "Will create a file system on partitions $suite5"
+#              disk1=p9
+#              disk2=p10
+#              disk3=p11
+#              disk4=p12
+#              diskLabel=$nvme1
+#              break
+#           ;;
+#           6)
+#              echo "Will create a file system on partitions $suite6"
+#              disk1=$one
+#              disk2=$two
+#              disk3=$three
+#              if [ ! -z "$four" ]; then disk4=$four; fi
+#              break
+#           ;;
+#           7)
+#              echo "Will create a file system on partitions $suite7"
+#              disk1=$five
+#              disk2=$six
+#              disk3=$seven
+#              if [ ! -z "$eight" ]; then disk4=$eight; fi
+#              break
+#           ;;
+#           $((${#options[@]}+1)))
+#              echo "Okay, will exit"
+#              exit 1
+#           ;;
+#           *) echo "Invalid option. Type 1, 2, 3, 4, 5, 6, 7 or 8"
+#              :
+#           ;;
+#        esac
+#    done
   fi
   if ! $as_root; then
     echo "If running as root, would mount these partitions:"
@@ -505,81 +515,84 @@ if [ "$LFS" = /mnt/lfs ]; then
     fi
 #
 #  exit 1
+    if ! $runit; then
+      echo "Partitions on sdb chosen. Will do nothing"
+    else
+      mount -v -t ext4 /dev/${diskLabel}${disk2} $LFS
+      if [ ! -d $LFS/boot ]; then mkdir -pv $LFS/boot; fi
+      mount -v -t ext4 /dev/${diskLabel}${disk1} $LFS/boot
+      if [ ! -d $LFS/home ]; then mkdir -pv $LFS/home; fi
+      mount -v -t ext4 /dev/${diskLabel}${disk3} $LFS/home
+      if [ ! -z "$disk4" ]; then
+        if [ ! -d $LFS/opt ]; then mkdir -pv $LFS/opt; fi
+        mount -v -t ext4 /dev/${diskLabel}${disk4} $LFS/opt
+      fi
+      if [ -e /dev/sda1 ]; then
+        echo "swap is partition /dev/sda1"
+        ${LFS}/usr/bin/swapon -v /dev/sda1
+      fi
 #
-    mount -v -t ext4 /dev/${diskLabel}${disk2} $LFS
-    if [ ! -d $LFS/boot ]; then mkdir -pv $LFS/boot; fi
-    mount -v -t ext4 /dev/${diskLabel}${disk1} $LFS/boot
-    if [ ! -d $LFS/home ]; then mkdir -pv $LFS/home; fi
-    mount -v -t ext4 /dev/${diskLabel}${disk3} $LFS/home
-    if [ ! -z "$disk4" ]; then
-      if [ ! -d $LFS/opt ]; then mkdir -pv $LFS/opt; fi
-      mount -v -t ext4 /dev/${diskLabel}${disk4} $LFS/opt
-    fi
-    if [ -e /dev/sdb13 ]; then
-      echo "swap is partition /dev/sdb13"
-      ${LFS}/usr/bin/swapon -v /dev/sdb13
-    fi
-    if [ -e /dev/nvme0n1p13 ]; then
-      echo "swap is partition /dev/nvme0n1p13"
-      ${LFS}/usr/bin/swapon -v /dev/nvme0n1p13
-    fi
-#
-    mount -v --bind /dev $LFS/dev
-#mount virtual kernel file systems
-    mount -v --bind /dev/pts $LFS/dev/pts
-    mount -vt proc proc $LFS/proc
-    mount -vt sysfs sysfs $LFS/sys
-    mount -vt tmpfs tmpfs $LFS/run
-    if [ -h $LFS/dev/shm ]; then
-      mkdir -pv $LFS/$(readlink $LFS/dev/shm)
-    fi
-    chmod 1777 $LFS/dev/shm
+      mount -v --bind /dev $LFS/dev
+# mount virtual kernel file systems
+      mount -v --bind /dev/pts $LFS/dev/pts
+      mount -vt proc proc $LFS/proc
+      mount -vt sysfs sysfs $LFS/sys
+      mount -vt tmpfs tmpfs $LFS/run
+      if [ -h $LFS/dev/shm ]; then
+        mkdir -pv $LFS/$(readlink $LFS/dev/shm)
+      fi
+      chmod 1777 $LFS/dev/shm
 # utmp numbering problem - 
 # utmp on Arch is group 997
 # utmp on LFS is group 13
 # utmp on Ubuntu is 43
 # so use the correct value below
-    useutmp=13 # LFS
-    touch $LFS/var/log/{btmp,lastlog,wtmp}
-    if [[ "${diskLabel}${disk2}" = nvme0n1p7 || "${diskLabel}${disk2}" = nvme1n1p7 ]]; then # Arch
-      useutmp=997
-    elif [ "${diskLabel}${disk2}" = nvme0n1p4 ]; then # Ububtu
-      useutmp=43
-    fi
-    chgrp -v $useutmp $LFS/var/log/{lastlog,btmp,wtmp}
-    chmod -v 664  $LFS/var/log/{lastlog,wtmp}
-    chmod -v 660  $LFS/var/log/btmp
-# if using Package User install, set some install files if using LFS partitions
-    ispkguser=true
-    echo "Installing as pkguser? [Y/n]"
-    read reply
-      case $reply in
-         [nN]|[nN][Oo])
-            ispkguser=false # installing as root
-         ;;
-      esac
-    if $ispkguser; then # check if Ubuntu or Arch partitions
-      if [[ "${diskLabel}${disk2}" != nvme0n1p4 && "${diskLabel}${disk2}" != nvme0n1p7 && "${diskLabel}${disk2}" != nvme1n1p7 ]]; then # LFS partition
-        chmod 1775 $LFS/var
-        chmod 1775 $LFS/var/{cache,lib,log}
-        if [ -d $LFS/srv ]; then
-          chgrp 9999 $LFS/srv # install group
-          chmod 1775 $LFS/srv
-        fi
+      useutmp=13 # LFS
+      touch $LFS/var/log/{btmp,lastlog,wtmp}
+      if [[ "${diskLabel}${disk2}" = nvme0n1p7 || "${diskLabel}${disk2}" = nvme1n1p7 ]]; then # Arch
+        useutmp=997
+      elif [ "${diskLabel}${disk2}" = nvme0n1p4 ]; then # Ububtu
+        useutmp=43
       fi
-    fi
-    mkdir -pv $LFS/run/lock
-    chmod 1777 $LFS/run/lock
+      chgrp -v $useutmp $LFS/var/log/{lastlog,btmp,wtmp}
+      chmod -v 664  $LFS/var/log/{lastlog,wtmp}
+      chmod -v 660  $LFS/var/log/btmp
+# if using Package User install, set some install files if using LFS partitions
+      ispkguser=true
+      echo "Installing as pkguser? [Y/n]"
+      read reply
+        case $reply in
+           [nN]|[nN][Oo])
+              ispkguser=false # installing as root
+           ;;
+        esac
+      if $ispkguser; then # check if Ubuntu or Arch partitions
+        if [[ "${diskLabel}${disk2}" != nvme0n1p4 && "${diskLabel}${disk2}" != nvme0n1p7 ]]; then # LFS partition
+          chmod 1775 $LFS/var
+          chmod 1775 $LFS/var/{cache,lib,log}
+          if [ -d $LFS/srv ]; then
+            chgrp 9999 $LFS/srv # install group
+            chmod 1775 $LFS/srv
+          fi
+          if [ -d $LFS/var/spool ]; then
+            chgrp 9999 $LFS/var/spool # install group
+            chmod 1775 $LFS/var/spool
+          fi
+        fi
+        mkdir -pv $LFS/run/lock
+        chmod 1777 $LFS/run/lock
+      fi
 # enter chroot
-    if [ -e /usr/bin/env ]; then
-      chroot "$LFS" /usr/bin/env -i        \
-        HOME=/root TERM="$TERM"            \
-        PS1='(lfs chroot) \u:\w\$ '        \
-        PATH=/bin:/usr/bin \
-        /bin/bash --login
-    else
-      echo "Can't enter chroot. No /usr/bin/env present"
-    fi
+      if [ -e /usr/bin/env ]; then
+        chroot "$LFS" /usr/bin/env -i        \
+          HOME=/root TERM="$TERM"            \
+          PS1='(lfs chroot) \u:\w\$ '        \
+          PATH=/bin:/usr/bin \
+          /bin/bash --login
+      else
+        echo "Can't enter chroot. No /usr/bin/env present"
+      fi
+    fi # test runit
   fi # test as_root
 else
   echo "Don't recognise variable LFS as $LFS"
